=== teema15135/xml-web-service-labs-kku/5930404259-teema-lab3/ptt.xsd
<?xml version="1.0"?>
<s:schema elementFormDefault="qualified" 
          xmlns:s="http://www.w3.org/2001/XMLSchema"
          targetNamespace="http://ptt.com">
    <s:element name="OilPrice">
        <s:complexType>
            <s:sequence>
                <s:element name="CurrentOilPrice">
                    <s:complexType>
                        <s:sequence>
                            <s:element minOccurs="0" maxOccurs="1" name="Language" type="s:string" />
                        </s:sequence>
                    </s:complexType>
                </s:element>
                <s:element name="CurrentOilPriceResponse">
                    <s:complexType>
                        <s:sequence>
                            <s:element minOccurs="0" maxOccurs="1" name="CurrentOilPriceResult" type="s:string" />
                        </s:sequence>
                    </s:complexType>
                </s:element>
                <s:element name="GetOilPrice">
                    <s:complexType>
                        <s:sequence>
                            <s:element minOccurs="0" maxOccurs="1" name="Language" type="s:string" />
                            <s:element minOccurs="1" maxOccurs="1" name="DD" type="s:short" />
                            <s:element minOccurs="1" maxOccurs="1" name="MM" type="s:short" />
                            <s:element minOccurs="1" maxOccurs="1" name="YYYY" type="s:short" />
                        </s:sequence>
                    </s:complexType>
                </s:element>
                <s:element name="GetOilPriceResponse">
                    <s:complexType>
                        <s:sequence>
                            <s:element minOccurs="0" maxOccurs="1" name="GetOilPriceResult" type="s:string" />
                        </s:sequence>
                    </s:complexType>
                </s:element>
            </s:sequence>
        </s:complexType>
    </s:element>
</s:schema>

=== teema15135/xml-web-service-labs-kku/5930404259-teema-lab3/ptt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<OilPrice
            xmlns="http://ptt.com"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://ptt.com ptt.xsd">
    <CurrentOilPrice>
        <Language>TH</Language>
    </CurrentOilPrice>
    <CurrentOilPriceResponse>
        <CurrentOilPriceResult>TH</CurrentOilPriceResult>
    </CurrentOilPriceResponse>
    <GetOilPrice>
        <Language>TH</Language>
        <DD>23</DD>
        <MM>08</MM>
        <YYYY>2018</YYYY>
    </GetOilPrice>
    <GetOilPriceResponse>
        <GetOilPriceResult>price</GetOilPriceResult>
    </GetOilPriceResponse>
</OilPrice>
