=== teema15135/xml-web-service-labs-kku/5930404259-teema-lab3/purchaseorder.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://tempuri.org/purchaseOrderSchema.xsd"
            xmlns:tns="http://tempuri.org/purchaseOrderSchema.xsd"
            elementFormDefault="qualified">

    <xsd:element name="purchaseOrder">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="shipTo" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="name" type="xsd:string"/>
                            <xsd:element name="building" type="xsd:string" minOccurs="0"/>
                            <xsd:element name="street" type="xsd:string"/>
                            <xsd:element name="city" type="xsd:string"/>
                            <xsd:element name="state" type="xsd:string"/>
                            <xsd:element name="zip" type="xsd:string"/>
                        </xsd:sequence>
                        <xsd:attribute name="country" type="xsd:string"/>
                        <xsd:attribute name="type" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="billTo" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="name" type="xsd:string"/>
                            <xsd:element name="building" type="xsd:string" minOccurs="0"/>
                            <xsd:element name="street" type="xsd:string"/>
                            <xsd:element name="city" type="xsd:string"/>
                            <xsd:element name="state" type="xsd:string"/>
                            <xsd:element name="zip" type="xsd:string"/>
                        </xsd:sequence>
                        <xsd:attribute name="country" type="xsd:string"/>
                        <xsd:attribute name="type" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>    
</xsd:schema>

=== teema15135/xml-web-service-labs-kku/5930404259-teema-lab3/purchaseorder.xml
<?xml version="1.0" encoding="utf-8"?>  
<purchaseOrder 
               xmlns="http://tempuri.org/purchaseOrderSchema.xsd"
               xmlns:xsi=
	"http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation=
	"http://tempuri.org/purchaseOrderSchema.xsd purchaseorder.xsd" >  
  <shipTo country="Thailand" type="express">  
    <name>name1</name>  
    <building>CP Tower</building>
    <street>street1</street>  
    <city>city1</city>  
    <state>state1</state>  
    <zip>10000</zip>  
  </shipTo>  
  <shipTo country="Japan">  
    <name>name2</name>  
    <street>street2</street>  
    <city>city2</city>  
    <state>state2</state>  
    <zip>20000</zip>  
  </shipTo>  
  <billTo country="Thailand">  
    <name>name1</name>  
    <street>street1</street>  
    <city>city1</city>  
    <state>state1</state>  
    <zip>1</zip>  
  </billTo>  
</purchaseOrder>
